### PR TITLE
Add logging if device family is not supported

### PR DESCRIPTION
**Pull request by dxdc**

### CODE REVIEW

**Comment by hjdhjd** [comment]
As it's written, this PR will surely spam anyone's logs that has an unsupported device since myQUpdateDeviceList is called several times a minute.

If you want to modify this to create a running list of denied devices and only notify the user when you add something to that list, I'll merge it in.

**Comment by dxdc** [comment]
>  I see how it might help to explicitly say "NOPE, we aren't going to add it, even though the API sees it".

Yeah, that was sort of the goal. 

> myQUpdateDeviceList is called several times a minute.

Why is it called so frequently? Seems it just needs to be called on startup, no? Or, at least, a lot less frequently.

**Comment by dxdc** [comment]
Ah, maybe it's just being updated since we have to retrieve the current state of all devices anyway?

Also, isn't this code duplicated? 


```js
    device = this.Devices!.find(
      (x: myQDevice) =>
        x.device_family &&
        x.device_family.indexOf("garagedoor") !== -1 &&
        x.serial_number &&
        hap.uuid.generate(x.serial_number) === uuid
    )!;

    // Iterate through the list and find the device that matches the UUID we seek.
    // This works because homebridge always generates the same UUID for a given input -
    // in this case the device serial number.
    if((device = this.Devices.find(
      (x: myQDevice) =>
        x.device_family &&
        (x.device_family.indexOf("garagedoor") !== -1) &&
        x.serial_number &&
        (hap.uuid.generate(x.serial_number) === uuid)
    )!) !== undefined) {
      return device;
    }
```

Couldn't it just be simplified to the following? I think no need to add the garagedoor check here since the uuid is matching?

```
    // Iterate through the list and find the device that matches the UUID we seek.
    // This works because homebridge always generates the same UUID for a given input -
    // in this case the device serial number.
    if((device = this.Devices.find(
      (x: myQDevice) =>
        x.device_family &&
        x.serial_number &&
        (hap.uuid.generate(x.serial_number) === uuid)
    )!) !== undefined) {
      return device;
    }
```

**Comment by hjdhjd** [comment]
I see you answered your own question...and yes, it's a dupe that's already been fixed in my working tree. :smile:

**Comment by hjdhjd** [comment]
When we ask myQ for it's status, it'll send us a list of everything it knows about. It's a logical time to deal with discovery...and disappearance.

I could conceptually move it out to just at startup time, but that's an artificial limitation that we don't need to impose on ourselves...so why do it? It's easy enough to do dynamic discovery so we do.

**Comment by hjdhjd** [comment]
On a completely unrelated topic...I'd welcome your thoughts on #71 - it's one I can't recreate and "mysteriously" seems to be fixed by installing an older version of the plugin and then reinstalling the most recent revision.

**Comment by dxdc** [comment]
@hjdhjd updated. let me know your thoughts. I moved the garage door check a bit later since it seems practical to do so (at least, if new devices are added in future). I'll look at #71.

**Comment by hjdhjd** [comment]
Looking...I was literally just sitting down to take this on. Wasn't sure if you were going to. :smile:

**Comment by hjdhjd** [comment]
I'll accept this and then modify it. There's no need to use the generated UUID. Keeping track of the device serial number, which we know to be there from an earlier check, will more than do the trick. Otherwise, looks good.

**Comment by dxdc** [comment]
I have a thought on #71:

This seems to be the problematic part of the code. 
```js
            if (!this.batteryStatusConfigured[accessory.UUID] && (this.doorPositionSensorBatteryStatus(accessory) !== -1)) {
                accessory
                    .getService(hap.Service.GarageDoorOpener)
                    .getCharacteristic(hap.Characteristic.StatusLowBattery)
```

So, `accessory.getService(hap.Service.GarageDoorOpener)` is undefined here. Maybe it's a race condition with how these are being initialized? Seems `hap.Service.AccessoryInformation` is fine at this point.

**Comment by dxdc** [comment]
>  Keeping track of the device serial number, which we know to be there from an earlier check, will more than do the trick.

Yeah, thought about that. Maybe add a check to confirm if `serial_number` exists too (just in case it is blank)? Otherwise, may get a little tricky if it's undefined.

**Comment by hjdhjd** [comment]
@dxdc I went down that path and it seems that it still hits for some people even with all the battery code commented out (as just a quick check).

**Comment by hjdhjd** [comment]
serial_number is already confirmed above it. We don't get that far down without it.

**Comment by hjdhjd** [comment]
@dxdc I think it's a race too...but what's the race here?

**Comment by dxdc** [comment]
> serial_number is already confirmed above it. We don't get that far down without it.

ah right :)

> @dxdc I went down that path and it seems that it still hits for some people even with all the battery code commented out (as just a quick check).

How could it produce the same line # of error then?

> I think it's a race too...but what's the race here?

Getting the opener set up vs. trying to update values? Either that, or maybe something funny in their devices (or... cached openers being loaded??)

**Comment by hjdhjd** [comment]
Okay...let's assume any of that is true. Why, for most people, does reloading the prior major release and then the current one solve the problem?

**Comment by hjdhjd** [comment]
That could, of course, be just a bizarre side effect of something else. But it's just plain weird.

**Comment by hjdhjd** [comment]
So let's talk about getting the opener setup versus trying to update the values. How could we get to where we are in the plugin to update values if the opener isn't already setup?

**Comment by dxdc** [comment]
> How could we get to where we are in the plugin to update values if the opener isn't already setup?

Well, if this fixes it:
> reloading the prior major release and then the current one solve the problem?

Then maybe it's not the issue. Hb has some code to automatically purge unused cachedAccessories. So, maybe there is some difference from that?

**Comment by hjdhjd** [comment]
None of the logic that touches those portions of code have been affected between releases. Aside from battery status, the only real changes was additional type checking in the code between those releases.

**Comment by dxdc** [comment]
What are the 2 commits of the releases? It would be helpful to see. I see you started tagging them :)

**Comment by hjdhjd** [comment]
That's why I started tagging them. :smile:

**Comment by hjdhjd** [comment]
Would be good to automate it, but I haven't taken the time to figure that out and set it up. If you know how to automate the release tagging process, would appreciate a pointer.

**Comment by hjdhjd** [comment]
Also...revised your patch above...take a look at the current master. I simplified.

**Comment by dxdc** [comment]
> Also...revised your patch above...take a look at the current master. I simplified.

Looks good. I don't like this kind of language:

```js
if(this.unsupportedDevices[device.serial_number]) {

          this.unsupportedDevices[device.serial_number] = true;
```

as you're introducing edge cases, and there's not a real reason to use a mixed object array. Why not,

```js
if(this.unsupportedDevices.indexOf(device.serial_number) === -1) {

          this.unsupportedDevices.push(device.serial_number);
```


> Would be good to automate it, but I haven't taken the time to figure that out and set it up. If you know how to automate the release tagging process, would appreciate a pointer.

There are many ways, here is one:
https://github.com/dgreif/ring/blob/2cb7930d58f459909e1fad469027fed6b4ad7992/package.json#L25

You can also try travis CI which integrates w/ Github

**Comment by hjdhjd** [comment]
@dxdc I'm not really introducing anymore edge cases than already exist. At the end of the day, virtually everything in this plugin depends on the **assumption** that serial numbers are unique. It's how UUIDs are generated, it's how a lot of things are validated for uniqueness. This is a simple, elegant solution without resorting to finds and other readability nightmares.

**Comment by dxdc** [comment]
> This is a simple, elegant solution without resorting to finds and other readability nightmares.

I take it back. Was just reviewing again, I thought you had left unsupportedDevices as an array, but see you moved it to an object. So, agree.

**Comment by hjdhjd** [comment]
Pushing it onto a traditional array is exactly what I am trying to avoid. The language gives me pseudo-associative arrays, why not use them? There's no reason not to. :smile:

**Comment by hjdhjd** [comment]
@dxdc So about that race condition...the block above adds the door opener service to the accessory. You think that it's reasonable that in the very next block it may not be fully configured yet, some of the time?

**Comment by hjdhjd** [comment]
@dxdc I've been looking at the Bond bridge you recommended. Assume you have some firsthand experience...how's the range? The website seems to have them perpetually on backorder but you can find them on Amazon. The pro product seems especially interesting...any experience?

**Comment by dxdc** [comment]
What is their pro product? I've had amazing luck with the range. No issues indoor, 100-200 ft+. Outdoor was another story. It worked but was intermittent. But, with some tweaking I finally got that to work flawlessly. You can do a lot with their API (e.g., tell it to repeat the Rf command a certain number of times).

**Comment by hjdhjd** [comment]
See the website. PoE, ethernet-based. Basically what I would want in something like this. :smile: Except it doesn't seem to exist anywhere for purchase.

**Comment by dxdc** [comment]
Oh, didn't know they had it. I have their USB one, which works great.

**Comment by hjdhjd** [comment]
I'm going to give it a shot and see...if it can help simplify my setup, I'm all for it. But I can't find the damn pro product.

**Pull request merged**
