### PR TITLE
Delay successive login attempts

### PR DESCRIPTION
**Pull request by shamoon**
This PR is dependent on https://github.com/hjdhjd/homebridge-myq2/pull/40 and part of fixing #38

### CODE REVIEW

**Comment by DMBlakeley** [comment]
Tested this PR and found by changing `myQ/19569` to `myQ/14041` along with change #40 resulted in the same condition as we originally had. Found 2 errors:

- `callback(error);` needs to be added after line 228
- Line 228 needs to be changed from `self.loginWaitInterval = 2 * ...` `this.loginWaitInterval = 2 * ...` for delay interval to progressively increment.

**Comment by shamoon** [comment]
As I said, this would need to be applied after your PR, which includes `callback`
I dont think that second change is needed, the plugin is written with the convention of using `self` which is a (perhaps outdated) JS convention for scoping `this` (see https://medium.com/@vijay.j.shekhawat/javascript-why-var-self-this-bbbaf98ab9d9) but anyway, I tried to respect the plugin as it is written, in which case `self` should work just fine.

**Comment by DMBlakeley** [comment]
@shamoon, I admit that I am a bit of a novice when it comes to JavaScript and I am learning from general knowledge, the many fine Homebridge examples, and a bit from trial and error. 

Now clear that your patch was on top of mine so see whey your patch did not include `callback(error); `. Thanks for clarifying.

With respect to `this` and `self` I believe that I have this right. I tested both and `this` worked, `self` did not. In this implementation `this` makes sense. Your `loginWaitInterval` routine is within the `MyQ2Platform.prototype.statePolling` function and the first statement is `var self = this;` `this.loginWaitInterval` moves value to outer loop and `var self = this;` brings value into the inner loop.

Believe that my archive at `DMBlakeley/homebridge-myq2` (Master branch) is the only one that has all of the patches incorporated.

**Comment by hjdhjd** [comment]
@DMBlakeley is right...but we also need a generally more elegant way to deal with this issue. How much of a problem is this right now for most is my question?

**Comment by DMBlakeley** [comment]
Changing myQ/14041 to myQ/19569 is a required change. 

The timer change prevents the MyQ servers from being hit every 5 seconds if there is an error. If not caught in a reasonably short time there was concern that the MyQ servers would block the user and this could be an issue. We are OK at the moment until you can come up with an alternate solution while you work on v5.

**Comment by hjdhjd** [comment]
@DMBlakeley I understand what the code is doing. :smile: I'm just asking what's the real world problem it's solving that people are experiencing en masse? In the refactor I'll share more broadly in the next week or so (hopefully!)...there's some intelligent backoff in login attempts. I've had my attention for the past few weeks refactoring another project [homebridge-doorbird](https://github.com/brownad/homebridge-doorbird) as a pleasant distraction from the day gig. Now it's time to really hunker down on this project and make some long overdue housekeeping. Thank you both for leaning in. Always welcome the assist!

**Comment by DMBlakeley** [comment]
The real world problem was as a result of the myQ/14041 call being incorrect the homebridge-myq2 app failed and in the process failed all of the remaining installed homebridge accessories. Quite a nasty impact. This additional change was intended to be safety net in case there was another issue.

Thanks for merging the PRs!

**Comment by hjdhjd** [comment]
Yeah...this plugin is based on a very old codebase that really just needs to be properly refactored. There's lots of hidden stuff here like that, such as the cached accessories messiness and a handful of other things. UGH! Thanks again all!

**Comment by shamoon** [comment]
Er, I think references to `self` work fine on line 228, I am testing the code right now (see below). And if they didn't, [the line before that](https://github.com/hjdhjd/homebridge-myq2/blob/9fcb9776404d39a615d979f71beeb93e0101c449/index.js#L227) which also uses `self` wouldn't work. They aren't loops, its a scope chain issue with anonymous functions.

```
[6/28/2020, 12:09:11 AM] [MyQ2] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 115
[6/28/2020, 12:09:11 AM] [MyQ2] Error logging into MyQ, delaying 20s before retrying.
[6/28/2020, 12:09:31 AM] [MyQ2] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 113
[6/28/2020, 12:09:31 AM] [MyQ2] Error logging into MyQ, delaying 40s before retrying.
[6/28/2020, 12:10:11 AM] [MyQ2] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 113
[6/28/2020, 12:10:11 AM] [MyQ2] Error logging into MyQ, delaying 80s before retrying.
[6/28/2020, 12:11:32 AM] [MyQ2] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 115
[6/28/2020, 12:11:32 AM] [MyQ2] Error logging into MyQ, delaying 160s before retrying.
```

Anyway, this PR is not super important it was just in case this or other random login issues happen the plugin doesnt keep hammering MyQ servers and risk the user having their IP blocked. If you are working on a version that does something like this then up to you whether to merge or not in the meantime.

And glad to hear about a bigger refactor—let us know if you need help with the overhaul youre working on!

**Comment by hjdhjd** [comment]
Closing and deprecating.

**Pull request closed without merging**
