### PR TITLE
Logic and style tweaks

### PR DESCRIPTION
**Pull request by dxdc**
- Fix .gitignore
- Add linting to code and address all linting warnings/errors (including removing unused variables)
- Simplify logic for doorTargetBias, doorCurrentBias

### CODE REVIEW

**Comment by dxdc** [comment]
@hjdhjd you didn't comment on the individual lines so I don't know what you're referring to? will work on the ones I can though.

**Comment by hjdhjd** [comment]
I barely use half the features on github...so bear with my learning curve here as I figure out the social coding etiquette. :smile:

**Comment by hjdhjd** [comment]
So the patches I’m good with: fixing the typos, updating from a series of ifs to a switch/case statement. The rest I have questions about. :smile:

Can you break this up into multiple PRs, or, if you prefer to just update this PR and you can be patient with me while I sort out how to cherry pick updates, I’d appreciate it.

**Comment by dxdc** [comment]
@hjdhjd made the following changes:

> Give me the argument for why single versus double quotes.
- It's a convention in languages that distinguish between these, so it's just a style preference. Used double quotes per single as you requested. For consistency, this was very mixed so you will see some single quotes changed to double.

> prefer extra parens where possible for improved readability (line 159 in the base).
- Fixed

> I’m also not a fan of excess carriage returns (lines 163-169 in your patch).
- Fixed

> Lines 199+...too many spaces, My coding convention is two spaces (no tabs). I believe that has 3.
- There were tabs in the latest commits which I fixed after rebasing against master. The spacing here should be correct now. The indenting had some issues in places before.

It may be easier for you to review the individual files and confirm:
- https://github.com/hjdhjd/homebridge-myq2/blob/81d4eaa65ae9847e396bf1cc99150fe880aaffd5/src/index.ts
- https://github.com/hjdhjd/homebridge-myq2/blob/81d4eaa65ae9847e396bf1cc99150fe880aaffd5/src/myq.ts

Lastly, 
> I barely use half the features on github...so bear with my learning curve here as I figure out the social coding etiquette.

This is how to comment on individual lines. Click the "+" icon.
Screen Shot 2020-07-05 at 4 51 36 PM

**Comment by dxdc** [comment]
> I’m not comfortable with this one. Why force the most recent versions upon all of us if we aren’t ready for them? If there’s a good reason, all for it.

I'm assuming (?) this is referring to package.json. This doesn't force new versions, just checks against them. They are dev dependencies.

**Comment by hjdhjd** [comment]
> > I’m not comfortable with this one. Why force the most recent versions upon all of us if we aren’t ready for them? If there’s a good reason, all for it.
> 
> I'm assuming (?) this is referring to package.json. This doesn't force new versions, just checks against them. They are dev dependencies.

Yeah, but this dev, for instance, isn’t using node 14 on all his platforms. :smile:

**Comment by hjdhjd** [comment]
@dxdc So here’s my question - if I merge this PR now, how can I see what are all the changes that are being merged in, since there are now multiple patches on top of patches here?

**Comment by dxdc** [comment]
> Yeah, but this dev, for instance, isn’t using node 14 on all his platforms.

Ah :) OK. Updated to the latest v10 package

> So here’s my question - if I merge this PR now, how can I see what are all the changes that are being merged in, since there are now multiple patches on top of patches here?

For the diff, you can click on : https://github.com/hjdhjd/homebridge-myq2/pull/67/files
or here: 
Screen Shot 2020-07-05 at 5 09 15 PM

**Comment by hjdhjd** [comment]
Sorry - brain fart. This happens when you get old. 😄

**Comment by hjdhjd** [comment]
Couple of more questions...so why reduce the import block as much as you chose to? I’m going off of the plugin template that the homebridge folks published.

Why swap out var for let...serves no functional purpose in the code?

**Comment by whreams** [comment]
Been watching for a while now… After a lackluster experience speaking to Chamberlain - very much appreciate the work being done here.  Great garage door opener - less than great homekit integration.  The work being done here bridges that gap.  
Sincerely - Thanks !

**Comment by dxdc** [comment]
> Couple of more questions...so why reduce the import block as much as you chose to? I’m going off of the plugin template that the homebridge folks published.

You should only import what is used in that file

> Why swap out var for let...serves no functional purpose in the code?

https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

**Comment by hjdhjd** [comment]
Fair enough...and thanks, sincerely, for making this better @dxdc.

**Comment by hjdhjd** [comment]
@whreams Thanks...it’s a fun little side project.

**Comment by whreams** [comment]
Thanks to Chamberlain, it continues to be….. ;)

**Pull request merged**
