### PR TITLE
Create config.schema.json

### PR DESCRIPTION
**Pull request by byronavory**
Adding config schema file to work with Homebridge Web UI plugin (homebridge-config-ui-x) and other type plugins.
https://github.com/oznu/homebridge-config-ui-x

### CODE REVIEW

**Comment by byronavory** [comment]
Thanks... I actually need to make a small edit.

**Comment by dppeak** [comment]
@hjdhjd Can we merge this?

**Comment by byronavory** [comment]
I apologize. I am still new to submitting. I thought that’s what I was asking for. Yes. It’s ready!

**Comment by dppeak** [comment]
@byronavory You've done everything right, I just don't have access in order to merge this PR.  Only @hjdhjd has write access.

Dave

**Comment by dppeak** [comment]
@hjdhjd Can you please merge this PR so we can get this in a new release.  Thanks.

**Comment by hjdhjd** [comment]
I'll merge this when I have the chance to validate. I do wonder how many people actually use these UIs though...what's the upside? Most people who know enough to setup homebridge are pretty comfortable with the command line. I'm genuinely curious.

**Comment by byronavory** [comment]
The primary reason this makes sense is specifically to elevate usability beyond those that are shell savvy. (i.e. I’ve setup homebridge for several family members for devices like door looks and cameras. If they get a new device, it would be nice for them to be able to add the device for themselves.). Simply put, this will expose your plugin to a far wider audience and increase your visibility.

Also, in my personal case, I am very comfortable using the shell. However, using the Web UI in conjunction with the shell simplifies and speeds up the troubleshooting process.

I could sit here all day and continue to present a case why this makes sense for users and yourself, but I would believe these two points should suffice.




Thanks,
Byron A. Couch
byronavory@gmail.com
 <mailto:byronavory@gmail.com>c: 614.530.6060 | f: 614.398.2332
https://www.linkedin.com//in/byroncouch <https://www.linkedin.com//in/byroncouch>

**Pull request merged**
