### PR TITLE
Feature: battery status (door position sensor)

### PR DESCRIPTION
**Pull request by shamoon**
@hjdhjd in your readme you mention that your device doesnt support battery status, I didn't realize there were myQ devices like that but I only have one (and it does, obviously). Anyway, it reports battery status for the door position sensor which I think is worth reporting in HK but I added checks i.e. if the device _doesnt_ seem to report battery status then its ignored.

🍻

### CODE REVIEW

**Comment by hjdhjd** [comment]
Thanks @shamoon ...reviewing...

**Comment by hjdhjd** [comment]
Will merge this in, and make some small tweaks. Thanks!

**Comment by hjdhjd** [comment]
@shamoon Random GH question...is there a straightforward way to edit your merge before I accept it, or do I need to accept it and then make changes after the fact?

**Comment by shamoon** [comment]
sorta, you cant make actual changes but can make comments on specific lines including code suggestions. Then the author of the PR can make the changes or whatever. But yes, the other thing is just to merge then modify. See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request

**Comment by hjdhjd** [comment]
That’s what I figured, but wanted to check to see if there was something I was missing. Thanks!

**Comment by sandeen** [comment]
Hey thanks for doing this, I was somewhere between Wyoming and Montana when I saw the notes about the battery status stuff getting removed during the big update.  :)

**Pull request merged**
