### PR TITLE
Reauthenticate security token (may address #79, #82)

### PR DESCRIPTION
**Pull request by dxdc**
- Untested, but a patch to allow security tokens to expire after a set interval
- May address #82 and #79

### CODE REVIEW

**Comment by hjdhjd** [comment]
I've got a series of other changes to commit as well, but I'm intrigued by this one...what leads you to believe the security token might be the culprit, or the additional logging around token longevity? I really haven't seen any issues on this front, and in perusing some of the other myQ reverse engineering projects, haven't seen anything there either. So I'm intrigued - what's the basis of your thinking?

**Comment by dxdc** [comment]
@hjdhjd I had the same issue as reported in the other issues, and restarting hb fixed it. Clearly, this call is failing:

```js
    const params = new URLSearchParams({ filterOn: "true" });
    const response = await this.myqFetch(myqApidev + "/Accounts/" + this.accountID + "/Devices?" + params, {
      method: "GET",
      headers: this.myqHeaders
    });
    if(!response) {
      this.log("myQ API error: unable to refresh. Will retry later.");
      return false;
    }
```

The only thing special here is `this.myqHeaders`, and the only thing special about that is the security token.

```
  private myqHeaders = {
    "Content-Type": "application/json",
    "User-Agent": myqAgent,
    ApiVersion: myqVersion,
    BrandId: "2",
    Culture: "en",
    MyQApplicationId: myqAppId,
    SecurityToken: ""
  };
```

At least, that is my analysis of it. Did you have a different thought? Unless there is something else going on, I can't understand why otherwise it will suddenly start failing and keep failing, but on hb restart the problem is immediately fixed.

**Comment by hjdhjd** [comment]
Wish I did. I agree with your analysis of which call is failing...that much is clear. It's the fix that's unclear to me.

Here's the rub...I've been running homebridge continuously for **days** without an issue with myQ.

How long does this issue take to manifest? Does the PR work to address the issue in your use case (glad it's you and that you can test and troubleshoot! :smile:)?

**Comment by dxdc** [comment]
I think it took 3-4 days in my case to manifest, not sure.  Did you try searching your logs? I wonder if it could go offline then back online.

The fix just retrieves another security token (and, then waits for the next polling interval to try it again). I'll have to report back on it after testing some more. I didn't test this one extensively yet.

**Comment by hjdhjd** [comment]
Yeah, I read through it and it seems innocuous enough...but does it actually fix it (for those experiencing it)? That's the question du jour. Arguably it's good hygiene to get a new token every so often anyway...

**Comment by hjdhjd** [comment]
Can you resolve the conflicts against the current master and I'll merge this one in? Thanks!

**Comment by dxdc** [comment]
> Yeah, I read through it and it seems innocuous enough...but does it actually fix it (for those experiencing it)? That's the question du jour

Agreed! I don't know yet..

> Can you resolve the conflicts against the current master and I'll merge this one in? Thanks!

Done!

**Comment by hjdhjd** [comment]
Flipping over to here @dxdc - prefer to keep code discussions to the PRs so the bug reports are cleaner to follow for end users. I refactored this somewhat across all the myQ logic to be a bit more holistic about how we deal with token refreshes. It was also a good time to just step back and reassess how I laid out this module logic and update it.

**Pull request merged**
