### PR TITLE
Added openers option to specify garage door openers similar to gateways

### PR DESCRIPTION
**Pull request by patricegautier**
Hi

New openers (LiftMaster 8500 in my case) have Wifi directly integrated and do no require a gateway.  

I added support for a new field called openers so you can specify those in the config, exactly like gateways

### CODE REVIEW

**Comment by patricegautier** [comment]
Bumping this to the top of the stack..

**Comment by hjdhjd** [comment]
@patricegautier - mind redoing this against the current version? I’ll merge it in then. Appreciated.

**Comment by patricegautier** [comment]
coming up

**Comment by patricegautier** [comment]
Ok conflicts are resolved.

**Comment by hjdhjd** [comment]
Package updated to v1.2.22

Should be all set. If someone wants to take a pass at more complete / verbose documentation on openers (and gateways for that matter) it would be appreciated. I'd like to update the README to better explain what these options are and *why* someone might want to use them.

Thanks for thee contribution @patricegautier!

**Comment by patricegautier** [comment]
Well here is why *I* am using those fields..  On my one MyQ account are openers and gateways for several properties.   The HomeKit view of things is very much geared to viewing one property at a time and it’s very confusing to have all the garage doors show up everywhere.  

So I use use to filter both gateways and openers so that only the right items show up in the right property HomeKit view.   This is only useful obviously if you have more than one property on the same MyQ account..

**Pull request merged**
