### PR TITLE
Fix/virtualgaragedooropener

### LINKED ISSUE #49: No Accessories showing up in v2.0.0
Used following config:

"platforms": [{
    "platform": "myQ",
    "email": "email@email.com",
    "password": "password"
}]

But no myQ accessories are being discovered or shown in home app.

Reset homebridge persist and accessories, still no go.

EDIT: started HB in insecure mode to see if any accessories show in the web interface, and no myQ accessories show up there either.

### PR DESCRIPTION
**Pull request by shamoon**
Maybe closes #49

### CODE REVIEW

**Comment by hjdhjd** [comment]
What the heck is the virtualgaragedooropener type? I haven't run into that before.

**Comment by shamoon** [comment]
I dont know if its because I dont have the homekit hub or what but thats what my device is, I have a feeling the same is true for others. But even if its not the problem for everyone out there it wont have any negative effects to include it... (and again, it works for me).

**Comment by pponce** [comment]
I’m not sure what it is meant to be :) but I see it when looking at the returned devices via the api calls and I’m also not seeing the garage door accessory show up in the home app with v2.05.

**Comment by hjdhjd** [comment]
@shamoon Fascinating. That must be the difference as I have both the hardware HB too. let's give this a whirl

**Comment by TheEngineerGuy** [comment]
Let me know when you want me to test.

**Comment by TheEngineerGuy** [comment]
Updated to 2.0.6  cleared accessories and persist cache, restarted HB. Still the same, no door in accessories list.

**Comment by hjdhjd** [comment]
2.0.7 should have it fixed.

**Comment by hjdhjd** [comment]
@shamoon Thanks for leaning in here...much appreciated. I'm still confused about why userId works for some, but accountID works for all.

**Comment by shamoon** [comment]
Yea, the dangers of working with undocumented APIs...

**Comment by TheEngineerGuy** [comment]
Updated to 2.0.7 cleared accessories and persist cache, restarted HB. Still the same, no door in accessories list.

```
[7/4/2020, 12:46:44 AM] [myQ] Successfully connected to the myQ API.
[7/4/2020, 12:46:45 AM] [myQ] myQ garagedoor device discovered: Garage Door - CGxxxxx.
[7/4/2020, 12:46:45 AM] [myQ] myQ gateway device discovered: Garage Door - GWxxxxxx.
```

**Comment by gizmotronic** [comment]
2.0.7 is working for me. Thank you!

```
[7/4/2020, 1:42:32 AM] [myQ] Successfully connected to the myQ API.
[7/4/2020, 1:42:32 AM] [myQ] myQ garagedoor device discovered: Garage Door - CGxxxxx.
[7/4/2020, 1:42:32 AM] [myQ] myQ gateway device discovered: Hub - GWxxxxx.
[7/4/2020, 1:42:32 AM] [myQ] Adding new myQ garagedoor device: Garage Door - CGxxxxx.
[7/4/2020, 1:46:14 AM] [myQ] Opening MyQ Garage Door.
[7/4/2020, 1:46:31 AM] [myQ] Closing MyQ Garage Door.
```

Hopefully I'm not about to get in trouble for this. :laughing:

**Comment by TheEngineerGuy** [comment]
See the "Adding new myQ garagedoor device" Is what I am not seeing.

**Comment by shamoon** [comment]
@TheEngineerGuy you seem to be the lone holdout unfortunately 😀 . Not sure if this will find the issue (and not sure if youre comfortable with this kinda stuff) but if you can add `this.log(this.myQ.Devices)` around line 139 of index.js and copy/paste your log (without any private info) it might help.

**Comment by TheEngineerGuy** [comment]
Yea, I can nano that in. Give me two minutes.

**Comment by TheEngineerGuy** [comment]
Ok line 139 is a ';' do I add it before that or after?

**Comment by adriancleung** [comment]
Hello, chiming in as I seem to have the same issue. My `device_type` is a `wifigaragedooropener`. Would that be needed in the condition as well?

**Comment by shamoon** [comment]
> Ok line 139 is a ';' do I add it before that or after?

After

**Comment by hjdhjd** [comment]
Yes it would

**Comment by shamoon** [comment]
> Hello, chiming in as I seem to have the same issue. My `device_type` is a `wifigaragedooropener`. Would that be needed in the condition as well?

Aha! I wondered if there would be others...

**Comment by hjdhjd** [comment]
Ditto...

**Comment by hjdhjd** [comment]
Sigh. How many of these bloody things are there.

**Comment by adriancleung** [comment]
Glad I can help.

**Comment by hjdhjd** [comment]
Adrian - did the logs show you the type?

**Comment by adriancleung** [comment]
Yup, showed that it was the wifigaragedooropener

**Comment by hjdhjd** [comment]
Alright, I think I'm going to take a pass at generalizing this to catch anymore rogue device types we don't know about yet...

**Comment by shamoon** [comment]
@hjdhjd You know, an alternative approach is instead of checking if the device_type _is_ X or Y or Z, we can just check to make sure it _isnt_ `hub`. Might be the shortest route... Then again at this point how many device_types can be left?!

**Comment by hjdhjd** [comment]
@shamoon My concern is when they add new types (locks, etc...) inadvertently breaking things that we don't know about. I think for the moment I'm going to just check to see if `garagedooropener` is in the type string somewhere and call it a day. If that doesn't work, plan B is the deny list approach and just outlawing gateways.

**Comment by TheEngineerGuy** [comment]
```



[7/4/2020, 1:09:54 AM] [myQ] Successfully connected to the myQ API.
[7/4/2020, 1:09:55 AM] [myQ] myQ garagedoor device discovered: Garage Door - CGxxxxxxxx.
[7/4/2020, 1:09:55 AM] [myQ] myQ gateway device discovered: Garage Door - GWxxxxxxxxxx.
[7/4/2020, 1:09:55 AM] [myQ] [
  {
    href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx',
    serial_number: 'CGxxxxxxxx',
    device_family: 'garagedoor',
    device_platform: 'myq',
    device_type: 'wifigaragedooropener',
    name: 'Garage Door',
    parent_device: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx',
    parent_device_id: 'GWxxxxxxxxxx',
    created_date: '2020-03-21T21:44:08.333',
    state: {
      gdo_lock_connected: false,
      attached_work_light_error_present: false,
      door_state: 'closed',
      open: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx/open',
      close: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx/close',
      last_update: '2020-07-04T03:49:14.8255024Z',
      passthrough_interval: '00:00:00',
      door_ajar_interval: '00:00:00',
      invalid_credential_window: '00:00:00',
      invalid_shutout_period: '00:00:00',
      is_unattended_open_allowed: true,
      is_unattended_close_allowed: true,
      aux_relay_delay: '00:00:00',
      use_aux_relay: false,
      aux_relay_behavior: 'None',
      rex_fires_door: false,
      command_channel_report_status: false,
      control_from_browser: false,
      report_forced: false,
      report_ajar: false,
      max_invalid_attempts: 0,
      online: true,
      last_status: '2020-07-04T07:07:06.3668007Z'
    }
  },
  {
    href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx',
    serial_number: 'GWxxxxxxxxxx',
    device_family: 'gateway',
    device_platform: 'myq',
    device_type: 'wifigdogateway',
    name: 'Garage Door',
    created_date: '2020-03-21T21:44:08.333',
    state: {
      firmware_version: '3.8',
      homekit_capable: false,
      homekit_enabled: false,
      learn: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx/learn',
      learn_mode: false,
      updated_date: '2020-07-04T02:56:08.8618092Z',
      physical_devices: [Array],
      pending_bootload_abandoned: false,
      online: true,
      last_status: '2020-07-04T02:56:04.8630529Z'
    }
  }
]
[7/4/2020, 1:10:09 AM] [myQ] [
  {
    href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx',
    serial_number: 'CGxxxxxxxx',
    device_family: 'garagedoor',
    device_platform: 'myq',
    device_type: 'wifigaragedooropener',
    name: 'Garage Door',
    parent_device: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx',
    parent_device_id: 'GWxxxxxxxxxx',
    created_date: '2020-03-21T21:44:08.333',
    state: {
      gdo_lock_connected: false,
      attached_work_light_error_present: false,
      door_state: 'closed',
      open: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx/open',
      close: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx/close',
      last_update: '2020-07-04T03:49:14.8255024Z',
      passthrough_interval: '00:00:00',
      door_ajar_interval: '00:00:00',
      invalid_credential_window: '00:00:00',
      invalid_shutout_period: '00:00:00',
      is_unattended_open_allowed: true,
      is_unattended_close_allowed: true,
      aux_relay_delay: '00:00:00',
      use_aux_relay: false,
      aux_relay_behavior: 'None',
      rex_fires_door: false,
      command_channel_report_status: false,
      control_from_browser: false,
      report_forced: false,
      report_ajar: false,
      max_invalid_attempts: 0,
      online: true,
      last_status: '2020-07-04T07:07:06.3668007Z'
    }
  },
  {
    href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx',
    serial_number: 'GWxxxxxxxxxx',
    device_family: 'gateway',
    device_platform: 'myq',
    device_type: 'wifigdogateway',
    name: 'Garage Door',
    created_date: '2020-03-21T21:44:08.333',
    state: {
      firmware_version: '3.8',
      homekit_capable: false,
      homekit_enabled: false,
      learn: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx/learn',
      learn_mode: false,
      updated_date: '2020-07-04T02:56:08.8618092Z',
      physical_devices: [Array],
      pending_bootload_abandoned: false,
      online: true,
      last_status: '2020-07-04T02:56:04.8630529Z'
    }
  }
]
[7/4/2020, 1:10:24 AM] [myQ] [
  {
    href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx',
    serial_number: 'CGxxxxxxxx',
    device_family: 'garagedoor',
    device_platform: 'myq',
    device_type: 'wifigaragedooropener',
    name: 'Garage Door',
    parent_device: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx',
    parent_device_id: 'GWxxxxxxxxxx',
    created_date: '2020-03-21T21:44:08.333',
    state: {
      gdo_lock_connected: false,
      attached_work_light_error_present: false,
      door_state: 'closed',
      open: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx/open',
      close: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/CGxxxxxxxx/close',
      last_update: '2020-07-04T03:49:14.8255024Z',
      passthrough_interval: '00:00:00',
      door_ajar_interval: '00:00:00',
      invalid_credential_window: '00:00:00',
      invalid_shutout_period: '00:00:00',
      is_unattended_open_allowed: true,
      is_unattended_close_allowed: true,
      aux_relay_delay: '00:00:00',
      use_aux_relay: false,
      aux_relay_behavior: 'None',
      rex_fires_door: false,
      command_channel_report_status: false,
      control_from_browser: false,
      report_forced: false,
      report_ajar: false,
      max_invalid_attempts: 0,
      online: true,
      last_status: '2020-07-04T07:07:06.3668007Z'
    }
  },
  {
    href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx',
    serial_number: 'GWxxxxxxxxxx',
    device_family: 'gateway',
    device_platform: 'myq',
    device_type: 'wifigdogateway',
    name: 'Garage Door',
    created_date: '2020-03-21T21:44:08.333',
    state: {
      firmware_version: '3.8',
      homekit_capable: false,
      homekit_enabled: false,
      learn: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxxxxxxxxx/devices/GWxxxxxxxxxx/learn',
      learn_mode: false,
      updated_date: '2020-07-04T02:56:08.8618092Z',
      physical_devices: [Array],
      pending_bootload_abandoned: false,
      online: true,
      last_status: '2020-07-04T02:56:04.8630529Z'
    }
  }
]


```

**Comment by adriancleung** [comment]
Tested by adding the `wifigaragedooropener` condition and it seems to work!

**Comment by hjdhjd** [comment]
@TheEngineerGuy yeah you've got the same problem as @adriancleung - fix coming soon...

**Comment by TheEngineerGuy** [comment]
k. Get done you n00bs geez!!! :)

**Comment by TheEngineerGuy** [comment]
@adriancleung You at UoA? Dude. I am like 10 blocks from the campus. Belgravia.

**Comment by shamoon** [comment]
> @shamoon My concern is when they add new types (locks, etc...) inadvertently breaking things that we don't know about. I think for the moment I'm going to just check to see if `garagedooropener` is in the type string somewhere and call it a day. If that doesn't work, plan B is the deny list approach and just outlawing gateways.

@hjdhjd good plan, at this point seems they're just adding as many possible euphemisms for "virtual" + garagedooropener so using that substring seems wise. Next will be digitalgaragedooropener, egaragedooropener, cybergaragedooropener, etc.

**Comment by TheEngineerGuy** [comment]
> > @shamoon My concern is when they add new types (locks, etc...) inadvertently breaking things that we don't know about. I think for the moment I'm going to just check to see if `garagedooropener` is in the type string somewhere and call it a day. If that doesn't work, plan B is the deny list approach and just outlawing gateways.
> 
> @hjdhjd good plan, at this point seems they're just adding as many possible euphemisms for "virtual" + garagedooropener so using that substring seems wise. Next will be digitalgaragedooropener, egaragedooropener, cybergaragedooropener, etc.

LOL!!!! Their portfolio manager needs to get paid. This is how you create job security.

**Comment by adriancleung** [comment]
> @adriancleung You at UoA? Dude. I am like 10 blocks from the campus. Belgravia.

Haha, yah, I attend UofA! Small world haha

**Comment by TheEngineerGuy** [comment]
> > @adriancleung You at UoA? Dude. I am like 10 blocks from the campus. Belgravia.
> 
> Haha, yah, I attend UofA! Small world haha

No, I didn't go here. Just live close by. Moved to town during oil boom. Small world indeed! In days of Covid this is how we get together. on GitHub.

**Comment by hjdhjd** [comment]
@TheEngineerGuy Try now gents...2.0.8 is out.

**Comment by TheEngineerGuy** [comment]
Bamm!!!! There you go.

**Comment by hjdhjd** [comment]
@shamoon LOL! Let's hope they never read this and start getting ideas on how to make our evenings even more fun trying to sort out how to reverse engineer their API. I just wish they'd create a proper way to monitor device state instead of all this bloody polling. I can't wait for the myQ supercybervirtualgaragedooropener

**Comment by TheEngineerGuy** [comment]
@hjdhjd One thing I miss from your previous plugin was the ability to see door opening, open, closing, closed log updates in HB Logs. Can we add that?

**Comment by pponce** [comment]
@hjdhjd 
Thanks for the work on this and the recent fixed. 
My ephemeralGaradoorOpener was found!

**Comment by hjdhjd** [comment]
@pponce you know, at this point, that sounds like a perfectly reasonable garage door opener type. :smile:

**Pull request merged**
