### PR TITLE
Minor v2 changes

### PR DESCRIPTION
**Pull request by dxdc**
@hjdhjd thanks for pushing this change! Really appreciate it.

Have a few minor suggestions here:
- Add .gitignore
- Remove forced "MyQ" prefix on the naming. Users can add their own name, and this shouldn't be overwritten by the plugin (no other plugins do this to my knowledge).
- Updated myAppId to the latest version (along with slight tweaks to header naming)

### CODE REVIEW

**Comment by hjdhjd** [comment]
All these are intentional choices except for the .gitignore. I'll add that in separately. Thanks.

**Comment by hjdhjd** [comment]
I'll also add for posterity - if you want to rename the accessory, you can do so in the Home app. The myQ prefix is one that I prefer to ensure people know which plugin generated it.

**Comment by dxdc** [comment]
> I'll also add for posterity - if you want to rename the accessory, you can do so in the Home app. The myQ prefix is one that I prefer to ensure people know which plugin generated it.

Yeah, I can rename it in the Home app, but it causes an issue with Node-RED and other plugins that use the accessory. I guess I don't see why you don't want the user to choose the name of the accessory?

> myAppId

You didn't want to use the newer version? `'JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu'` appears to be deprecated.

**Comment by hjdhjd** [comment]
With respect to naming, I gave you my reasoning...you just don't like it. :smile:

The AppId isn't deprecated to my knowledge, and judging from the handful of other MyQ API apps out there using the same one, it seems fine.

Where'd you get the additional AppId and what makes you believe this one is deprecated, since it seems to be working just fine?

**Comment by dxdc** [comment]
> With respect to naming, I gave you my reasoning...you just don't like it. 😄

Fair enough 😆 

> Where'd you get the additional AppId and what makes you believe this one is deprecated, since it seems to be working just fine?

There are many methods to reverse API's...
I imagine they'll transition to the new one at some point, similar to how v4 was deprecated for a while (but working), but finally isn't.

It's also very interesting to me that the mobile apps have no issue connected to the API's at all. Not sure what the difference is exactly.

**Comment by hjdhjd** [comment]
Well, the mobile apps have one big thing going for them at the moment:

They use certificate pinning to ensure their traffic can't be easily sniffed. You'd need to use a jailbroken iOS device or rooted-Android device, and then disable pinning in the respective app bundles, to be able to cleanly do it.

Sucks.

**Pull request closed without merging**
